name: Build & Push Gitpod Image

on:
  push:
    paths:
      - '.gitpod.yml'
      - '.gitpod.Dockerfile'
      - 'Dockerfile'
      - '.github/workflows/gitpod-image.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Decide Dockerfile
        id: df
        run: |
          if [ -f ".gitpod.Dockerfile" ]; then
            echo "file=.gitpod.Dockerfile" >> $GITHUB_OUTPUT
          else
            echo "file=Dockerfile" >> $GITHUB_OUTPUT
          fi

      - name: Set image tag
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}-gitpod:latest" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ steps.df.outputs.file }}
          push: true
          tags: ${{ env.IMAGE }}
          provenance: false
